---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: netbox
  description: NetBox with plugins
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: radiorabe/container-image-netbox
  links:
    - url: https://github.com/netbox-community/netbox-docker/
      title: https://github.com/netbox-community/netbox-docker/
spec:
  type: container
  lifecycle: experimental
  owner: it-reaktion
